<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Files\" />
    <Folder Include="Ai\" />
    <Folder Include="Clock\" />
    <Folder Include="Pdf\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic.SDK" Version="5.10.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageReference Include="PdfPig" Version="0.1.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartFund.Application\SmartFund.Application.csproj" />
    <ProjectReference Include="..\SmartFund.Domain\SmartFund.Domain.csproj" />
  </ItemGroup>

</Project>
