// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartFund.Persistence.DbContext;

#nullable disable

namespace SmartFund.Persistence.Migrations
{
    [DbContext(typeof(SmartFundDbContext))]
    [Migration("20260327104807_AddMultiUserSupport")]
    partial class AddMultiUserSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartFund.Domain.Agent.PendingAgentAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("PendingAgentActions", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.Agreement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("SignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SignedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TrancheId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrancheId", "Version")
                        .IsUnique();

                    b.ToTable("Agreements", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("LedgerTransactionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReversedByAuditEntryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReversesAuditEntryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("LedgerTransactionId");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.Deal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DealCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DealCode")
                        .IsUnique();

                    b.ToTable("Deals", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.InsuranceWallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("DealId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReserveAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.HasIndex("ReserveAccountId");

                    b.HasIndex("Type", "DealId");

                    b.ToTable("InsuranceWallets", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.Investor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Investors", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.LedgerAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ReferenceType", "ReferenceId");

                    b.ToTable("LedgerAccounts", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LedgerTransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("LedgerTransactionId");

                    b.ToTable("LedgerEntries", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.LedgerTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PostedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<long?>("ReversesTransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SequenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LedgerTransactions", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.LoanApplication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LoanTermMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PurposeCategory")
                        .HasColumnType("int");

                    b.Property<string>("PurposeDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ReviewedByUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("LoanApplications", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.Tranche", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("DealId")
                        .HasColumnType("bigint");

                    b.Property<int>("EarlyWithdrawalPolicy")
                        .HasColumnType("int");

                    b.Property<long>("InvestorId")
                        .HasColumnType("bigint");

                    b.Property<long>("LiabilityAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NoticeDays")
                        .HasColumnType("int");

                    b.Property<int>("PayoutType")
                        .HasColumnType("int");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RoiRate")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("RoiType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrancheCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.HasIndex("InvestorId");

                    b.HasIndex("LiabilityAccountId");

                    b.HasIndex("TrancheCode")
                        .IsUnique();

                    b.ToTable("Tranches", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalBudget.Entities.Budget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CategoryId", "Period")
                        .IsUnique();

                    b.ToTable("PersonalBudgets", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalBudget.Entities.BudgetTracking", b =>
                {
                    b.Property<long>("BudgetId")
                        .HasColumnType("bigint");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BudgetId", "Year", "Month");

                    b.HasIndex("Year", "Month");

                    b.ToTable("PersonalBudgetTracking", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.BankCategorizationRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AutoPostCredits")
                        .HasColumnType("bit");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("bit");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRegex")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMatchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchCount")
                        .HasColumnType("int");

                    b.Property<string>("MatchText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("IsActive", "Priority");

                    b.ToTable("BankCategorizationRules", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.BankImportedTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AmountKobo")
                        .HasColumnType("bigint");

                    b.Property<long>("ConnectedBankAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ExtractedMerchant")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdempotencyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPending")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReversal")
                        .HasColumnType("bit");

                    b.Property<long?>("LinkedPersonalTransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("MonoTransactionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedNarration")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RawNarration")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReversalOfMonoId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TransferPairImportId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedBankAccountId");

                    b.HasIndex("IdempotencyHash")
                        .IsUnique();

                    b.HasIndex("LinkedPersonalTransactionId");

                    b.HasIndex("MonoTransactionId", "ConnectedBankAccountId")
                        .IsUnique();

                    b.HasIndex("Status", "ImportedAtUtc");

                    b.ToTable("BankImportedTransactions", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.ConnectedBankAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ConnectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("LastKnownBalanceKobo")
                        .HasColumnType("bigint");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonoAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("PersonalWalletId")
                        .HasColumnType("bigint");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("int");

                    b.Property<int>("TotalTransactionsSynced")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAtUtc");

                    b.HasIndex("MonoAccountId")
                        .IsUnique();

                    b.HasIndex("PersonalWalletId");

                    b.HasIndex("UserId");

                    b.ToTable("ConnectedBankAccounts", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.PersonalCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Type", "Name")
                        .IsUnique();

                    b.ToTable("PersonalCategories", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.PersonalFinanceSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastResetAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LaunchDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PersonalFinanceSettings", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.PersonalGoal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("SavedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalGoals", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.PersonalTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("LedgerTransactionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceBankImportedTransactionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceConnectedBankAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("WalletId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LedgerTransactionId");

                    b.HasIndex("SourceBankImportedTransactionId");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("PersonalTransactions", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.PersonalWallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("LedgerAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LedgerAccountId");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalWallets", (string)null);
                });

            modelBuilder.Entity("SmartFund.Persistence.DbContext.LedgerDailySequence", b =>
                {
                    b.Property<string>("DateKey")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.HasKey("DateKey");

                    b.ToTable("LedgerDailySequences", (string)null);
                });

            modelBuilder.Entity("SmartFund.Persistence.DbContext.TrancheDailySequence", b =>
                {
                    b.Property<string>("DateKey")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.HasKey("DateKey");

                    b.ToTable("TrancheDailySequences", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.Agreement", b =>
                {
                    b.HasOne("SmartFund.Domain.Entities.Tranche", null)
                        .WithMany()
                        .HasForeignKey("TrancheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.InsuranceWallet", b =>
                {
                    b.HasOne("SmartFund.Domain.Entities.Deal", null)
                        .WithMany()
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartFund.Domain.Entities.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("ReserveAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.LedgerEntry", b =>
                {
                    b.HasOne("SmartFund.Domain.Entities.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFund.Domain.Entities.LedgerTransaction", null)
                        .WithMany("Entries")
                        .HasForeignKey("LedgerTransactionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("SmartFund.Domain.ValueObjects.Money", "Credit", b1 =>
                        {
                            b1.Property<long>("LedgerEntryId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Credit");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("CreditCurrency");

                            b1.HasKey("LedgerEntryId");

                            b1.ToTable("LedgerEntries");

                            b1.WithOwner()
                                .HasForeignKey("LedgerEntryId");
                        });

                    b.OwnsOne("SmartFund.Domain.ValueObjects.Money", "Debit", b1 =>
                        {
                            b1.Property<long>("LedgerEntryId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Debit");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("DebitCurrency");

                            b1.HasKey("LedgerEntryId");

                            b1.ToTable("LedgerEntries");

                            b1.WithOwner()
                                .HasForeignKey("LedgerEntryId");
                        });

                    b.Navigation("Credit")
                        .IsRequired();

                    b.Navigation("Debit")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.LoanApplication", b =>
                {
                    b.HasOne("SmartFund.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartFund.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.Tranche", b =>
                {
                    b.HasOne("SmartFund.Domain.Entities.Deal", null)
                        .WithMany()
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartFund.Domain.Entities.Investor", null)
                        .WithMany()
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFund.Domain.Entities.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("LiabilityAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalBudget.Entities.Budget", b =>
                {
                    b.HasOne("SmartFund.Domain.PersonalFinance.Entities.PersonalCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFund.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalBudget.Entities.BudgetTracking", b =>
                {
                    b.HasOne("SmartFund.Domain.PersonalBudget.Entities.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.BankCategorizationRule", b =>
                {
                    b.HasOne("SmartFund.Domain.PersonalFinance.Entities.PersonalCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFund.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.BankImportedTransaction", b =>
                {
                    b.HasOne("SmartFund.Domain.PersonalFinance.Entities.ConnectedBankAccount", null)
                        .WithMany()
                        .HasForeignKey("ConnectedBankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFund.Domain.PersonalFinance.Entities.PersonalTransaction", null)
                        .WithMany()
                        .HasForeignKey("LinkedPersonalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.ConnectedBankAccount", b =>
                {
                    b.HasOne("SmartFund.Domain.PersonalFinance.Entities.PersonalWallet", null)
                        .WithMany()
                        .HasForeignKey("PersonalWalletId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartFund.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.PersonalCategory", b =>
                {
                    b.HasOne("SmartFund.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.PersonalFinanceSettings", b =>
                {
                    b.HasOne("SmartFund.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.PersonalGoal", b =>
                {
                    b.HasOne("SmartFund.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.PersonalTransaction", b =>
                {
                    b.HasOne("SmartFund.Domain.PersonalFinance.Entities.PersonalCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartFund.Domain.Entities.LedgerTransaction", null)
                        .WithMany()
                        .HasForeignKey("LedgerTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFund.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFund.Domain.PersonalFinance.Entities.PersonalWallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.PersonalFinance.Entities.PersonalWallet", b =>
                {
                    b.HasOne("SmartFund.Domain.Entities.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFund.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.LedgerTransaction", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
