// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartFund.Persistence.DbContext;

#nullable disable

namespace SmartFund.Persistence.Migrations
{
    [DbContext(typeof(SmartFundDbContext))]
    [Migration("20260222020501_AddTranches")]
    partial class AddTranches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartFund.Domain.Entities.LedgerAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ReferenceType", "ReferenceId");

                    b.ToTable("LedgerAccounts", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LedgerTransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("LedgerTransactionId");

                    b.ToTable("LedgerEntries", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.LedgerTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PostedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<long?>("ReversesTransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SequenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LedgerTransactions", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.Tranche", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("DealId")
                        .HasColumnType("bigint");

                    b.Property<int>("EarlyWithdrawalPolicy")
                        .HasColumnType("int");

                    b.Property<long>("InvestorId")
                        .HasColumnType("bigint");

                    b.Property<long>("LiabilityAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NoticeDays")
                        .HasColumnType("int");

                    b.Property<int>("PayoutType")
                        .HasColumnType("int");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RoiRate")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("RoiType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrancheCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("LiabilityAccountId");

                    b.HasIndex("TrancheCode")
                        .IsUnique();

                    b.ToTable("Tranches", (string)null);
                });

            modelBuilder.Entity("SmartFund.Persistence.DbContext.LedgerDailySequence", b =>
                {
                    b.Property<string>("DateKey")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.HasKey("DateKey");

                    b.ToTable("LedgerDailySequences", (string)null);
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.LedgerEntry", b =>
                {
                    b.HasOne("SmartFund.Domain.Entities.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartFund.Domain.Entities.LedgerTransaction", null)
                        .WithMany("Entries")
                        .HasForeignKey("LedgerTransactionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("SmartFund.Domain.ValueObjects.Money", "Credit", b1 =>
                        {
                            b1.Property<long>("LedgerEntryId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Credit");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("CreditCurrency");

                            b1.HasKey("LedgerEntryId");

                            b1.ToTable("LedgerEntries");

                            b1.WithOwner()
                                .HasForeignKey("LedgerEntryId");
                        });

                    b.OwnsOne("SmartFund.Domain.ValueObjects.Money", "Debit", b1 =>
                        {
                            b1.Property<long>("LedgerEntryId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Debit");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("DebitCurrency");

                            b1.HasKey("LedgerEntryId");

                            b1.ToTable("LedgerEntries");

                            b1.WithOwner()
                                .HasForeignKey("LedgerEntryId");
                        });

                    b.Navigation("Credit")
                        .IsRequired();

                    b.Navigation("Debit")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.Tranche", b =>
                {
                    b.HasOne("SmartFund.Domain.Entities.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("LiabilityAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartFund.Domain.Entities.LedgerTransaction", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
